[versions]
androidGradle = "8.2.2"
kotlin = "1.9.23"
kotlinCoroutines = "1.3.7"
androidX = "1.0.0"
androidXConstraintLayout = "2.0.2"
androidXKtxCore = "1.0.2"
androidXLifecycle = "2.2.0-alpha01"
androidRoom = "2.1.0"
androidRoomTesting = "2.1.0"
robolectric = "3.5.1"
mockitoCore = "2.12.0"
junit = "4.12"
ktlint = "0.9.2"
aboutLibraries = "7.0.1"

[libraries]
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradle" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidX" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXKtxCore" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "androidX" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidX" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidX" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidX" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidXLifecycle" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidRoom" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidXConstraintLayout" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries", version.ref = "aboutLibraries" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.13" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.4" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "androidRoomTesting" }
ktlint = { group = "com.github.shyiko", name = "ktlint", version.ref = "ktlint" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
