[versions]
androidGradle = "8.9.2"
kotlin = "2.1.21"
kotlinCoroutines = "1.10.2"
androidxAppCompat = "1.7.1"
androidxCardView = "1.0.0"
androidxConstraintLayout = "2.2.1"
androidxFragment = "1.8.8"
androidxLifecycle = "2.9.1"
androidxKtxCore = "1.16.0"
androidxMaterial = "1.12.0"
androidxRecyclerView = "1.4.0"
androidxRoom = "2.7.1"
robolectric = "4.14.1"
mockitoCore = "5.18.0"
junit = "4.13.2"
ktlint = "0.9.2"
aboutLibraries = "7.0.1"

[libraries]
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradle" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxKtxCore" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "androidxFragment" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidxCardView" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerView" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidxMaterial" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries", version.ref = "aboutLibraries" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.13" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.4" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "androidxRoom" }
ktlint = { group = "com.github.shyiko", name = "ktlint", version.ref = "ktlint" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
